### ISSUE TITLE
Assertion `entries != NULL' failed.

### ISSUE THREAD

**Issue by mj1618** [rggibson/open-pure-cfr#4]
Hi, 

having an issue which might just be misunderstanding the cli. I'm just trying to run a limit holdem 2p game.

# ./pure_cfr games/holdem.limit.2p.reverse_blinds.game test.limit --status=1 --max-walltime=30
GAME_FILE games/holdem.limit.2p.reverse_blinds.game
OUTPUT_PREFIX test.limit
RNG_SEEDS 6 12 1983 28
CARD_ABSTRACTION NULL
ACTION_ABSTRACTION NULL
NUM_THREADS 1
STATUS_FREQ_SECONDS 1
DUMP_TIMER 2147483647 1 0
MAX_WALLTIME_SECONDS 30
DO_AVERAGE TRUE
PARAMETERS_END
Initializing Pure CFR machine... pure_cfr: entries.hpp:119: Entries_der<T>::Entries_der(size_t, size_t, T*) [with T = int; size_t = long unsigned int]: Assertion `entries != NULL' failed.
Aborted

**Comment by rggibson** [comment]
This is actually the intended behaviour.  The assert you are hitting is due to not enough RAM being available to run pure CFR with the specified game abstraction.  For a large game like limit hold'em, the NULL card abstraction is infeasible.  To avoid hitting the assert, you will need to specify a different card abstraction with the --card-abs option.  BLIND should work just fine, though you will probably want to implement your own card abstraction if you would like the program to actually look at its cards.  You can do so by creating a new subclass of the CardAbstraction class in card_abstraction.hpp.  Note that the NULL card abstraction can be used just fine for toy games, such as Kuhn poker.
