### ISSUE TITLE
Card abstraction

### ISSUE THREAD

**Issue by markudevelop** [rggibson/open-pure-cfr#5]
Hello Richard,

What does card --card-abs=<NULL|BLIND> option really do? By reading the papers I understood that using CFR you could use a "bucket" system which basically allows you to group the solution instead of holding all possible solution (in the case of nolimit holdem there are too much).

Does it mean that currently open-pure-cfr doesn't save any cards data and doesn't really has this "bucket" way of grouping cards? so how it even work by BLIND cards, I'm a bit confused.

Thanks! :)

**Comment by rggibson** [comment]
You are right, CFR typically employs a "bucket" system (i.e. card abstraction) to reduce the size of the state space.  What this means is that on a given round, hands are merged into buckets using some choice of card abstraction method.  CFR then treats all hands in the same bucket as a single "card state."  In other words, for every hand falling into the same bucket, CFR must use the same action probabilities at a given betting sequence.

Now, --card-abs=<NULL|BLIND> selects the card abstraction used by the Pure CFR algorithm.  NULL here means that we put every hand into its own bucket (which doesn't reduce the state space at all), even if the hand only differs by a suit isomorphism.  BLIND is the opposite: all hands are merged into a single bucket so that CFR effectively does not look at the cards at all.

These are the only 2 card abstractions currently implemented, and honestly neither of them are that useful outside of toy games like Kuhn Poker.  With that said, you can implement your own card abstraction by creating a subclass of the `CardAbstraction` class found in `card_abstraction.hpp`.  Hope that helps.
